apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-rollouts-cd-demo
  namespace: argo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fastapi-rollouts-cd-demo
  template:
    metadata:
      labels:
        app: fastapi-rollouts-cd-demo
    spec:
      containers:
        - name: fastapi-rollouts-cd-demo
          image: 192.168.0.112:5000/fastapi-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 30 }
        - setWeight: 100
